version: '2'

services:
    # Database service
    db:
        image: mysql:5.7
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306

    # Backend service
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PORT: ${MYSQL_PORT}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
            - ./php7-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./php7-fpm/supervisord.conf:/etc/supervisor/conf.d/captum.conf
            - ./php7-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf

    # Web-server service
    nginx:
        build: nginx
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
            - ./php7-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./logs/nginx/:/var/log/nginx
